services:
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - app-network
  # ---------- Databases ----------
  #################################
  # To create a new service database:
  # 
  # 1. Copy and paste user-db
  # 2. Rename:
  #          - service name key (user-db)
  #          - container_name
  #          - POSTGRES_DB
  #          - volumes
  #             - if using pgsql follow below
  #                   - first line change the user-db-data to the service-db-data
  #                   - the second line, ./services/user-service/...
  #                                                   ^ ^ ^ --> change to the service name you are adding in.
  # Example changes:
  #   user-db                -> question-db
  #   user-db-data           -> question-db-data
  #   ./services/user-service -> ./services/question-service
  ################################
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: userdb
    volumes:
      - user-db-data:/var/lib/postgresql/data
      - ./services/user-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  question-db:
    image: postgres:15
    container_name: question-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: questiondb
    volumes:
      - question-db-data:/var/lib/postgresql/data
      - ./services/question-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  collab-db:
    image: postgres:15
    container_name: collab-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: collabdb
    volumes:
      - collab-db-data:/var/lib/postgresql/data
      - ./services/collab-service-rooms/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  match-db:
    image: redis:7-alpine
    container_name: match-db
    restart: always
    networks:
      - app-network

  # ---------- Backends ----------
  #################################
  # Creating a new backend service
  #
  # 1. Copy the user-service block.
  # 2. Rename:
  #    - service key (user-service)
  #    - container_name
  #    - build path
  #    - DATABASE_URL host + db name (remove if your service does not need)
  #    - ports
  #
  # Example:
  #   user-service -> order-service
  #   ./services/user-service -> ./services/order-service
  #   user-db:5432/userdb -> order-db:5432/orderdb
  #
  # NOTE: in environment, PORT can be 3000. change ports
  # Example: ports:
  #            - "3000:3000" -> "3001:3000"
  #                ^ left side is for local, right side is for docker.
  #################################
  user-service:
    build: ./services/user-service
    container_name: user-service
    depends_on:
      - user-db
    environment:
      DATABASE_URL: postgres://postgres:secret@user-db:5432/userdb
      JWT_SECRET: supersecretjwtkey
      EMAIL_PEPPER: secretpepper
      EMAIL_ENCRYPTION_KEY: 6f2e9b4c1a7d3f5b8e0c2d1f9a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app-network

  question-service:
    build: ./services/question-service
    container_name: question-service
    depends_on:
      - question-db
    environment:
      DATABASE_URL: postgres://postgres:secret@question-db:5432/questiondb
      PORT: 3001
      JWT_SECRET: supersecretjwtkey
    ports:
      - "3001:3001"
    networks:
      - app-network

  # collab-service:
  #   build: ./services/collab-service
  #   container_name: collab-service
  #   depends_on:
  #     - collab-db
  #     - redis
  #   environment:
  #     DATABASE_URL: postgres://postgres:secret@collab-db:5432/collabdb
  #     REDIS_URL: redis://redis:6379
  #     PORT: 3002
  #     JWT_SECRET: supersecretjwtkey
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - app-network

  collab-service-rooms:
    build: ./services/collab-service-rooms
    container_name: collab-service-rooms
    depends_on:
      - collab-db
    environment:
      DATABASE_URL: postgres://postgres:secret@collab-db:5432/collabdb
      PORT: 3002
      JWT_SECRET: supersecretjwtkey
    ports:
      - "3002:3002"
    networks:
      - app-network

  collab-service-websocket:
    build: ./services/collab-service-websocket
    container_name: collab-service-websocket
    depends_on:
      - collab-db
      - collab-service-rooms
    environment:
      HOST: 0.0.0.0
      PORT: 3004
      JWT_SECRET: supersecretjwtkey
    ports:
      - "3004:3004"
    networks:
      - app-network
  
  match-service:
    build: ./services/match-service
    container_name: match-service
    depends_on:
      - match-db
    environment:
      REDIS_URL: redis://match-db:6379
      PORT: 3003
    ports:
      - "3003:3003"
    networks:
      - app-network
  ai-service:
    build: ./services/ai-service
    container_name: ai-service
    environment:
      - PORT=3006
      - GEMINI_API_KEY=${GEMINI_AI_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GEMINI_AI_API_KEY}
    ports:
      - "3006:3006"
    networks:
      - app-network

  # ---------- Frontend ----------
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - user-service
      - question-service
      - collab-service-rooms
      - match-service
      - collab-service-websocket
      - ai-service
    environment:
      VITE_USER_SERVICE_URL: http://user-service:3000
      VITE_QUESTION_SERVICE_URL: http://question-service:3001
      VITE_COLLAB_SERVICE_ROOMS_URL: http://collab-service-rooms:3002
      VITE_MATCH_SERVICE_URL: http://match-service:3003
      VITE_COLLAB_SERVICE_WEBSOCKET_URL: http://collab-service-websocket:3004
      VITE_AI_SERVICE_URL: http://ai-service:3006
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  user-db-data:
  question-db-data:
  collab-db-data:

networks:
    app-network:
      driver: bridge